from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam

class TransferedModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # use this model by removing the last layer, adding dense layers and an output layer

        basic_model = models.load_model('''results/basic_model_10_epochs_timestamp_1785871988.keras''')

        layers_list = basic_model.layers[:-1]

        self.model = models.Sequential(layers_list)

        for layer in self.model.layers:
             layer.trainable = False

        layers.MaxPooling2D(2),
        layers.Conv2D(24, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(2)

        self.model.add(layers.Dense(128, activation='relu'))
        self.model.add(layers.Dropout(0.3,name='uhh'))
        self.model.add(layers.Dense(categories_count, activation='sigmoid'))
        #self.model.build(input_shape)


    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=RMSprop(learning_rate=0.001),
            loss="categorical_crossentropy",
            metrics=["accuracy"]
        )
